name: Minecord
version: '${project.version}'
main: de.epsdev.minecord.Minecord
api-version: 1.21
authors: [ LillySchramm ]
description: Connects your server chat with a discord channel.
website: https://gitlab.eps-dev.de/Lilly/minecrod.git
commands:
  linkDiscord:
    description: Link your discord account to your minecraft name.
    usage: /<command>
  unlinkDiscord:
    description: Remove the link to your discord account.
    usage: /<command>